In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df1 = pd.read_parquet("C:/Users/qkrtl/10th/00_Project/04_final/02_parquet_file/04_temp_parquet_files/analysis_output/erangel_features.parquet")

In [ ]:
df1.T

,0,1,2,3,4,5,6,7,8,9,...,234235,234236,234237,234238,234239,234240,234241,234242,234243,234244
matchId,000c936c-b00b-47f0-9e1b-493d589f99bd,000c936c-b00b-47f0-9e1b-493d589f99bd,000c936c-b00b-47f0-9e1b-493d589f99bd,000c936c-b00b-47f0-9e1b-493d589f99bd,000c936c-b00b-47f0-9e1b-493d589f99bd,000c936c-b00b-47f0-9e1b-493d589f99bd,000c936c-b00b-47f0-9e1b-493d589f99bd,000c936c-b00b-47f0-9e1b-493d589f99bd,000c936c-b00b-47f0-9e1b-493d589f99bd,000c936c-b00b-47f0-9e1b-493d589f99bd,...,ffd8f1e1-4a98-456d-a9e6-e06251cdbea9,ffd8f1e1-4a98-456d-a9e6-e06251cdbea9,ffd8f1e1-4a98-456d-a9e6-e06251cdbea9,ffd8f1e1-4a98-456d-a9e6-e06251cdbea9,ffd8f1e1-4a98-456d-a9e6-e06251cdbea9,ffd8f1e1-4a98-456d-a9e6-e06251cdbea9,ffd8f1e1-4a98-456d-a9e6-e06251cdbea9,ffd8f1e1-4a98-456d-a9e6-e06251cdbea9,ffd8f1e1-4a98-456d-a9e6-e06251cdbea9,ffd8f1e1-4a98-456d-a9e6-e06251cdbea9
accountId,account.0038d4bb0dcc4a05b68d39589da0236e,account.0616e81ecec241c2915f1bbc52b6958e,account.0901bd6b4a6942d894cddab5aa0907f5,account.0d2472cda90944c69b0111471bed1af2,account.10cfdd7235c54acab7252a396d392466,account.11347af861ef41baa255a9f11990a300,account.13e58593efb440f68433359c47b982fd,account.148814d1227a448a9344ffdc26e5168a,account.1583f1ee7dcc4bbdb764aa2d251a89ed,account.16caa74dce934511987bc2d684b48241,...,account.df6cd7f0c2564f8ba411c493b1cb1887,account.e0818362272f4d8cba82c51e1e8efcd9,account.e32f77c6cde2461eb42e81361c4b1bf1,account.e9b488acacc041d2a8f181afc1f29812,account.e9c13c0ecb9b4aa2a591289b32e15bde,account.ea825a4d327c4f5095718884baf72158,account.f0a6f8d1e24c4b1881bb826ac3d82fd0,account.f0d3c4aaa34142eeb9535ba6e8142e35,account.f54aaf14429943cbab09c30ebc66812b,account.fdbaf316a9cf4cd58e3d57ab14771ac2
rotation_timing_score,NaN,0.566873,NaN,NaN,0.587462,0.494048,0.525425,0.619443,0.652191,0.629495,...,0.511402,0.663665,0.552297,0.654975,0.597029,0.400469,0.623848,0.59657,0.603032,0.397845
vehicle_use_ratio,0.0,0.065359,0.0,0.0,0.24183,0.352273,0.237288,0.338028,0.058824,0.18,...,0.153285,0.339806,0.520408,0.301587,0.17757,0.0,0.086957,0.275362,0.5,0.0
bluezone_exposure_ratio,0.0,0.176471,0.0,0.0,0.0,0.363636,0.0,0.0,0.058824,0.0,...,0.0,0.038835,0.0,0.0,0.0,0.019608,0.0,0.0,0.0,0.039216
safezone_proximity_mean,2783.81673,1492.732054,2212.186712,2074.297796,488.632477,1972.025832,1933.381689,2046.04716,1271.143475,1746.370711,...,462.249515,904.161839,832.725898,1302.304286,1442.046346,1343.216307,2585.770063,1248.004042,2485.269221,1504.741686
safezone_edge_ratio,0.004783,0.007371,0.003801,0.003564,0.003953,0.007626,0.00388,0.004879,0.006052,0.003415,...,0.003617,0.003774,0.00359,0.006135,0.004693,0.003301,0.004885,0.00598,0.005146,0.003694
altitude_variance,125.964431,16076.135434,223.228081,145.951916,4683.979033,1810.887261,19415.658264,904.550655,17975.482076,1181.784372,...,1468.514833,1440.665539,1260.618197,8385.80372,806.846488,238.897323,3657.629532,2567.464768,650.00121,551.549301
survival_time,130.0,1513.0,199.0,160.0,1514.0,866.0,576.0,696.0,1127.0,488.0,...,1342.0,1004.0,954.0,1233.0,1044.0,493.0,443.0,1353.0,483.0,492.0
total_movement,12359.044434,796011.108843,31892.819979,7575.659322,730057.638147,713904.221071,575528.633966,464981.665878,256375.608684,277737.296232,...,430775.480796,609128.877405,652667.039405,875386.184751,419975.186744,43539.670229,209864.173686,719803.56919,558092.030181,56943.525992
drop_distance_from_path,1379.728838,89.725873,258.88342,953.250124,1612.792046,668.445751,719.379786,794.126571,1217.598059,384.293781,...,759.674246,35.563966,426.029319,713.584712,989.268716,50.563339,1701.602212,1367.330088,1544.51124,147.995981
drop_x,608259.625,433051.0625,457920.90625,546866.875,424951.78125,383373.8125,514952.9375,704869.5625,522459.03125,627747.625,...,361877.53125,215387.375,302229.125,584996.875,149395.75,411028.6875,162343.96875,345719.375,689577.0,395164.1875
drop_y,598414.375,636454.125,628402.4375,254159.453125,325888.96875,572639.0,623736.25,330888.0625,243367.84375,377667.1875,...,404218.40625,395918.4375,396509.8125,129427.117188,314229.90625,300776.6875,608055.0,174894.9375,329620.46875,286473.25
early_enemy_density,4.0,4.0,4.0,3.0,2.0,0.0,0.0,4.0,3.0,1.0,...,0.0,0.0,0.0,0.0,4.0,3.0,0.0,0.0,0.0,6.0
max_vehicle_distance,6333.902745,7427.493728,7232.288893,3701.789423,5090.524821,7176.731962,6925.433432,3489.929235,3813.181472,4219.434453,...,6126.887622,7355.818058,6593.802872,5296.685214,7649.121937,5180.542662,8935.534096,5383.844714,3207.988277,5261.125993
kills,0.0,3.0,0.0,0.0,5.0,0.0,0.0,2.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
damageDealt,0.0,235.884,0.0,0.0,695.2859,21.925003,0.0,116.89659,0.0,183.86143,...,327.09116,54.094547,41.489,16.13575,0.0,0.0,0.0,270.82126,0.0,99.99999
winPlace,15.0,2.0,14.0,7.0,3.0,10.0,13.0,12.0,7.0,13.0,...,2.0,7.0,7.0,5.0,3.0,16.0,12.0,1.0,15.0,16.0
win_flag,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
top3_flag,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,...,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
timeSurvived,208.0,1610.0,265.0,190.0,1572.0,964.0,618.0,791.0,508.0,570.0,...,1403.0,1065.0,1014.0,1343.0,1102.0,593.0,492.0,1412.0,531.0,593.0
walkDistance,238.57861,4001.6692,538.5615,284.91815,3775.5532,2299.9685,1376.107,2002.4917,1130.4342,1227.6993,...,3094.5154,1817.6829,1257.1531,3378.7327,2561.4512,1171.7073,1193.2747,3249.2717,713.1383,1222.8229
rideDistance,0.0,5127.8877,0.0,0.0,5931.6284,5671.699,4582.8354,3655.413,162.5964,2334.5535,...,3255.3057,5550.5605,6872.3037,7447.207,2988.7717,0.0,863.38605,5575.123,5593.6997,0.0
heals,0.0,13.0,0.0,0.0,6.0,6.0,0.0,0.0,0.0,1.0,...,6.0,1.0,0.0,3.0,0.0,0.0,0.0,4.0,0.0,0.0
boosts,1.0,7.0,1.0,0.0,9.0,5.0,1.0,0.0,2.0,3.0,...,8.0,1.0,0.0,2.0,2.0,1.0,0.0,7.0,1.0,3.0
kill_rate,0.0,0.111801,0.0,0.0,0.19084,0.0,0.0,0.151707,0.0,0.105263,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.042493,0.0,0.10118
move_speed,0.01147,0.024855,0.020323,0.014996,0.024018,0.023859,0.022267,0.025316,0.022253,0.021539,...,0.022056,0.017067,0.012398,0.025158,0.023244,0.019759,0.024254,0.023012,0.01343,0.020621
heal_boost_use,1.0,20.0,1.0,0.0,15.0,11.0,1.0,0.0,2.0,4.0,...,14.0,2.0,0.0,5.0,2.0,1.0,0.0,11.0,1.0,3.0

In [8]:
df2 = pd.read_parquet("C:/Users/qkrtl/10th/00_Project/04_final/02_parquet_file/04_temp_parquet_files/analysis_output/erangel_clustered.parquet")
df2.T

,0,1,2,3,4,5,6,7,8,9,...,213516,213517,213518,213519,213520,213521,213522,213523,213524,213525
matchId,000c936c-b00b-47f0-9e1b-493d589f99bd,000c936c-b00b-47f0-9e1b-493d589f99bd,000c936c-b00b-47f0-9e1b-493d589f99bd,000c936c-b00b-47f0-9e1b-493d589f99bd,000c936c-b00b-47f0-9e1b-493d589f99bd,000c936c-b00b-47f0-9e1b-493d589f99bd,000c936c-b00b-47f0-9e1b-493d589f99bd,000c936c-b00b-47f0-9e1b-493d589f99bd,000c936c-b00b-47f0-9e1b-493d589f99bd,000c936c-b00b-47f0-9e1b-493d589f99bd,...,ffd8f1e1-4a98-456d-a9e6-e06251cdbea9,ffd8f1e1-4a98-456d-a9e6-e06251cdbea9,ffd8f1e1-4a98-456d-a9e6-e06251cdbea9,ffd8f1e1-4a98-456d-a9e6-e06251cdbea9,ffd8f1e1-4a98-456d-a9e6-e06251cdbea9,ffd8f1e1-4a98-456d-a9e6-e06251cdbea9,ffd8f1e1-4a98-456d-a9e6-e06251cdbea9,ffd8f1e1-4a98-456d-a9e6-e06251cdbea9,ffd8f1e1-4a98-456d-a9e6-e06251cdbea9,ffd8f1e1-4a98-456d-a9e6-e06251cdbea9
accountId,account.0038d4bb0dcc4a05b68d39589da0236e,account.0616e81ecec241c2915f1bbc52b6958e,account.0901bd6b4a6942d894cddab5aa0907f5,account.0d2472cda90944c69b0111471bed1af2,account.10cfdd7235c54acab7252a396d392466,account.11347af861ef41baa255a9f11990a300,account.13e58593efb440f68433359c47b982fd,account.148814d1227a448a9344ffdc26e5168a,account.1583f1ee7dcc4bbdb764aa2d251a89ed,account.16caa74dce934511987bc2d684b48241,...,account.df6cd7f0c2564f8ba411c493b1cb1887,account.e0818362272f4d8cba82c51e1e8efcd9,account.e32f77c6cde2461eb42e81361c4b1bf1,account.e9b488acacc041d2a8f181afc1f29812,account.e9c13c0ecb9b4aa2a591289b32e15bde,account.ea825a4d327c4f5095718884baf72158,account.f0a6f8d1e24c4b1881bb826ac3d82fd0,account.f0d3c4aaa34142eeb9535ba6e8142e35,account.f54aaf14429943cbab09c30ebc66812b,account.fdbaf316a9cf4cd58e3d57ab14771ac2
rotation_timing_score,0.54413,0.566873,0.54413,0.54413,0.587462,0.494048,0.525425,0.619443,0.652191,0.629495,...,0.511402,0.663665,0.552297,0.654975,0.597029,0.400469,0.623848,0.59657,0.603032,0.397845
vehicle_use_ratio,0.0,0.065359,0.0,0.0,0.24183,0.352273,0.237288,0.338028,0.058824,0.18,...,0.153285,0.339806,0.520408,0.301587,0.17757,0.0,0.086957,0.275362,0.5,0.0
bluezone_exposure_ratio,0.0,0.176471,0.0,0.0,0.0,0.363636,0.0,0.0,0.058824,0.0,...,0.0,0.038835,0.0,0.0,0.0,0.019608,0.0,0.0,0.0,0.039216
safezone_proximity_mean,2783.81673,1492.732054,2212.186712,2074.297796,488.632477,1972.025832,1933.381689,2046.04716,1271.143475,1746.370711,...,462.249515,904.161839,832.725898,1302.304286,1442.046346,1343.216307,2585.770063,1248.004042,2485.269221,1504.741686
safezone_edge_ratio,0.004783,0.007371,0.003801,0.003564,0.003953,0.007626,0.00388,0.004879,0.006052,0.003415,...,0.003617,0.003774,0.00359,0.006135,0.004693,0.003301,0.004885,0.00598,0.005146,0.003694
altitude_variance,125.964431,16076.135434,223.228081,145.951916,4683.979033,1810.887261,19415.658264,904.550655,17975.482076,1181.784372,...,1468.514833,1440.665539,1260.618197,8385.80372,806.846488,238.897323,3657.629532,2567.464768,650.00121,551.549301
survival_time,130.0,1513.0,199.0,160.0,1514.0,866.0,576.0,696.0,1127.0,488.0,...,1342.0,1004.0,954.0,1233.0,1044.0,493.0,443.0,1353.0,483.0,492.0
total_movement,12359.044434,796011.108843,31892.819979,7575.659322,730057.638147,713904.221071,575528.633966,464981.665878,256375.608684,277737.296232,...,430775.480796,609128.877405,652667.039405,875386.184751,419975.186744,43539.670229,209864.173686,719803.56919,558092.030181,56943.525992
drop_distance_from_path,1379.728838,89.725873,258.88342,953.250124,1612.792046,668.445751,719.379786,794.126571,1217.598059,384.293781,...,759.674246,35.563966,426.029319,713.584712,989.268716,50.563339,1701.602212,1367.330088,1544.51124,147.995981
drop_x,608259.625,433051.0625,457920.90625,546866.875,424951.78125,383373.8125,514952.9375,704869.5625,522459.03125,627747.625,...,361877.53125,215387.375,302229.125,584996.875,149395.75,411028.6875,162343.96875,345719.375,689577.0,395164.1875
drop_y,598414.375,636454.125,628402.4375,254159.453125,325888.96875,572639.0,623736.25,330888.0625,243367.84375,377667.1875,...,404218.40625,395918.4375,396509.8125,129427.117188,314229.90625,300776.6875,608055.0,174894.9375,329620.46875,286473.25
early_enemy_density,4.0,4.0,4.0,3.0,2.0,0.0,0.0,4.0,3.0,1.0,...,0.0,0.0,0.0,0.0,4.0,3.0,0.0,0.0,0.0,6.0
max_vehicle_distance,6333.902745,7427.493728,7232.288893,3701.789423,5090.524821,7176.731962,6925.433432,3489.929235,3813.181472,4219.434453,...,6126.887622,7355.818058,6593.802872,5296.685214,7649.121937,5180.542662,8935.534096,5383.844714,3207.988277,5261.125993
kills,0.0,3.0,0.0,0.0,5.0,0.0,0.0,2.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
damageDealt,0.0,235.884,0.0,0.0,695.2859,21.925003,0.0,116.89659,0.0,183.86143,...,327.09116,54.094547,41.489,16.13575,0.0,0.0,0.0,270.82126,0.0,99.99999
winPlace,15.0,2.0,14.0,7.0,3.0,10.0,13.0,12.0,7.0,13.0,...,2.0,7.0,7.0,5.0,3.0,16.0,12.0,1.0,15.0,16.0
win_flag,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
top3_flag,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,...,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
timeSurvived,208.0,1610.0,265.0,190.0,1572.0,964.0,618.0,791.0,508.0,570.0,...,1403.0,1065.0,1014.0,1343.0,1102.0,593.0,492.0,1412.0,531.0,593.0
walkDistance,238.57861,4001.6692,538.5615,284.91815,3775.5532,2299.9685,1376.107,2002.4917,1130.4342,1227.6993,...,3094.5154,1817.6829,1257.1531,3378.7327,2561.4512,1171.7073,1193.2747,3249.2717,713.1383,1222.8229
rideDistance,0.0,5127.8877,0.0,0.0,5931.6284,5671.699,4582.8354,3655.413,162.5964,2334.5535,...,3255.3057,5550.5605,6872.3037,7447.207,2988.7717,0.0,863.38605,5575.123,5593.6997,0.0
heals,0.0,13.0,0.0,0.0,6.0,6.0,0.0,0.0,0.0,1.0,...,6.0,1.0,0.0,3.0,0.0,0.0,0.0,4.0,0.0,0.0
boosts,1.0,7.0,1.0,0.0,9.0,5.0,1.0,0.0,2.0,3.0,...,8.0,1.0,0.0,2.0,2.0,1.0,0.0,7.0,1.0,3.0
kill_rate,0.0,0.118969,0.0,0.0,0.198151,0.0,0.0,0.172414,0.0,0.122951,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.044346,0.0,0.121951
move_speed,1.83522,2.644857,2.706339,1.780738,2.49376,2.655853,2.389075,2.877143,1.003047,2.515777,...,2.305898,1.810441,1.317771,2.740254,2.453497,2.376688,2.693622,2.401531,1.476477,2.485412
heal_boost_use,1.0,20.0,1.0,0.0,15.0,11.0,1.0,0.0,2.0,4.0,...,14.0,2.0,0.0,5.0,2.0,1.0,0.0,11.0,1.0,3.0
segment,C1_edge,C3_guerilla,uncertain,uncertain,C3_guerilla,C1_edge,C1_edge,C2_aggro,C1_edge,uncertain,...,C3_guerilla,C3_guerilla,C0_center,C1_edge,C2_aggro,C0_center,C1_edge,C1_edge,C1_edge,C0_center
margin,2.458747,0.858365,0.164578,0.392074,1.591133,3.831563,0.796343,1.442504,1.230153,0.420327,...,3.689527,0.872322,1.464017,1.470695,0.897525,2.982971,3.579615,1.724915,5.31816,2.311926
persona,🌿 외곽 운영형,🦅 게릴라 운영형,❓ 혼합형,❓ 혼합형,🦅 게릴라 운영형,🌿 외곽 운영형,🌿 외곽 운영형,⚔️ 중앙 교전형,🌿 외곽 운영형,❓ 혼합형,...,🦅 게릴라 운영형,🦅 게릴라 운영형,🏃 중앙 점령형,🌿 외곽 운영형,⚔️ 중앙 교전형,🏃 중앙 점령형,🌿 외곽 운영형,🌿 외곽 운영형,🌿 외곽 운영형,🏃 중앙 점령형
score_C0_center,-0.828001,1.136801,1.108985,-0.315813,-2.203619,0.261022,-0.302615,-0.841326,-2.410666,-0.99329,...,-0.159685,-1.216358,-0.202999,-2.256346,-0.955084,3.421796,-3.491951,-2.470894,-2.904943,4.049951
score_C1_edge,2.417661,3.024886,-0.857193,0.076261,1.978691,4.21482,0.493728,0.263265,1.126913,-0.321693,...,0.563078,-2.010315,-1.873401,1.525428,-0.005538,-2.477786,3.485005,3.505891,3.386696,-2.204708
score_C2_aggro,-0.041086,1.301143,1.273563,-0.460552,0.478735,-0.15161,-0.554218,1.705769,-1.634204,0.098634,...,-0.679744,-1.427463,-2.170976,-0.024237,0.891987,0.438825,-0.09461,-0.490553,-1.931464,1.738024
score_C3_guerilla,-2.387254,3.883252,-1.591876,-1.428119,3.569824,0.383257,-1.508796,-3.329045,-0.10324,-0.423891,...,4.252605,-0.344035,-1.667016,0.054732,-1.168476,-0.157943,-1.906582,1.780976,-3.609898,-0.551316
umap_x,1.50605,1.456635,3.228923,2.308949,-1.787795,2.992776,0.76145,-3.060827,-0.240229,-1.829235,...,-0.839988,-2.281551,-3.06144,-0.707147,-3.771477,2.65064,-5.412776,-3.298454,-4.993152,0.994601
umap_y,-3.105672,13.276103,-0.74826,-1.61759,9.684284,9.052448,14.833974,7.131692,14.996672,6.765146,...,7.516987,6.939813,5.592222,13.16663,7.405972,2.6972,6.871462,9.063846,6.16161,4.714261