In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [9]:
df_tele = pd.read_csv("csv_file/1match_telemetry.csv")
df_tele

C:\Users\for\AppData\Local\Temp\ipykernel_19896\1994294700.py:1: DtypeWarning: Columns (0,4,17,25,26,27,42,47,49,50,54,55,56,57,59,60,61,110,122,124,125,127,128,136,137,138,139,140,141,142,143,144,145,146,147,149,152,153,154,155,172,173,174,175,176,177,184,185,186,190,198,199,200,201,202,203,204,205,206,207,208,209,211,212,220,221,222,223,224,225,226,227,228,229,230,231,233,234,242,243,244,245,246,247,248,249,250,251,252,253,255,256,257,264,265,266,271,274,275,282,283,287,288,289,297,298,299,301,302,303,304,307,308,316,317,318,320,321,322,323,327,328,329) have mixed types. Specify dtype option on import or set low_memory=False.
  df_tele = pd.read_csv("csv_file/1match_telemetry.csv")

,MatchId,PingQuality,_D,_T,accountId,common.isGame,character.name,character.teamId,character.health,character.location.x,...,instigator.isInVehicle,instigator.zone,instigator.type,instigator.isDBNO,attacker,wheelIndex,carePackageUniqueId,carePackageName,allWeaponStats,gameResultOnFinished.results
0,match.bro.competitive.pc-2018-39.kakao.squad.k...,NaN,2026-01-27T01:39:18.8256559Z,LogMatchDefinition,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,2026-01-27T01:38:09.968Z,LogPlayerLogin,account.98475b7e0b6e42a091a8174fee812abb,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,2026-01-27T01:38:09.994Z,LogPlayerCreate,NaN,0.0,wwvvwvvwvwvw,11.0,100.0,452889.12500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,2026-01-27T01:38:09.994Z,LogPlayerLogin,account.74ba67fc414742c896450c6d302b4208,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,2026-01-27T01:38:10.007Z,LogPlayerCreate,NaN,0.0,audgh3859,6.0,100.0,451526.90625,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36167,NaN,NaN,2026-01-27T02:04:51.828Z,LogHeal,NaN,6.5,DTT_0214,13.0,100.0,428261.15625,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36168,NaN,NaN,2026-01-27T02:04:55.269Z,LogHeal,NaN,6.5,ililliililililli,13.0,100.0,440267.09375,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36169,NaN,NaN,2026-01-27T02:04:59.711Z,LogHeal,NaN,6.5,ohbaby_gak,13.0,100.0,430248.40625,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36170,NaN,NaN,2026-01-27T02:04:59.811Z,LogHeal,NaN,6.5,DTT_0214,13.0,100.0,428261.15625,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36171,NaN,NaN,2026-01-27T02:05:03.251Z,LogHeal,NaN,6.5,ililliililililli,13.0,100.0,440267.09375,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df_match = pd.read_csv("csv_file/100matches_data.csv")
df_match

,matchId,mapName,gameMode,createdAt,DBNOs,assists,boosts,damageDealt,deathType,headshotKills,...,revives,rideDistance,roadKills,swimDistance,teamKills,timeSurvived,vehicleDestroys,walkDistance,weaponsAcquired,winPlace
0,9c3b2882-2adf-4ce5-9056-e818718f6195,Baltic_Main,solo,2026-01-26T23:41:48Z,0,0,7,170.85225,byzone,1,...,0,2256.599000,0,0.0,0,1184,0,4067.791000,11,20
1,9c3b2882-2adf-4ce5-9056-e818718f6195,Baltic_Main,solo,2026-01-26T23:41:48Z,0,0,0,397.84018,byplayer,0,...,0,2750.859600,0,0.0,0,1067,0,1568.328100,13,31
2,9c3b2882-2adf-4ce5-9056-e818718f6195,Baltic_Main,solo,2026-01-26T23:41:48Z,0,0,5,1871.53660,alive,5,...,0,5775.330600,4,0.0,0,1511,0,2363.590800,13,1
3,9c3b2882-2adf-4ce5-9056-e818718f6195,Baltic_Main,solo,2026-01-26T23:41:48Z,0,0,4,1217.24460,byplayer,2,...,0,79.235176,0,0.0,0,1480,0,4400.385000,8,4
4,7f63076c-8f55-43a1-8e9d-0135e976a924,Baltic_Main,solo,2026-01-26T23:45:48Z,0,0,5,322.61300,byplayer,1,...,0,3854.556000,0,0.0,0,1310,0,1745.032200,8,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2092,0d8e5d95-afe8-4fd0-9edf-c782a78823c1,Chimera_Main,squad,2026-01-27T07:37:44Z,1,0,0,179.93295,byplayer,0,...,0,0.000000,0,0.0,0,647,0,1968.728900,5,13
2093,0d8e5d95-afe8-4fd0-9edf-c782a78823c1,Chimera_Main,squad,2026-01-27T07:37:44Z,1,0,7,267.32376,byplayer,1,...,0,0.000000,0,0.0,0,1167,0,3187.406200,11,3
2094,0d8e5d95-afe8-4fd0-9edf-c782a78823c1,Chimera_Main,squad,2026-01-27T07:37:44Z,5,1,8,934.68110,alive,3,...,0,2.365976,0,0.0,0,1253,0,2858.578000,8,1
2095,0d8e5d95-afe8-4fd0-9edf-c782a78823c1,Chimera_Main,squad,2026-01-27T07:37:44Z,1,0,0,146.20000,byplayer,1,...,0,0.000000,0,0.0,0,492,0,2018.418600,4,14
2096,bcb6eaac-42ee-4678-a4bf-f239e8d66e23,Tutorial_Main,solo,2026-01-27T07:57:40Z,0,0,0,0.00000,logout,0,...,0,0.000000,0,0.0,0,161,0,10.306934,0,1

In [10]:
df_match.T

,0,1,2,3,4,5,6,7,8,9,...,2087,2088,2089,2090,2091,2092,2093,2094,2095,2096
matchId,9c3b2882-2adf-4ce5-9056-e818718f6195,9c3b2882-2adf-4ce5-9056-e818718f6195,9c3b2882-2adf-4ce5-9056-e818718f6195,9c3b2882-2adf-4ce5-9056-e818718f6195,7f63076c-8f55-43a1-8e9d-0135e976a924,7f63076c-8f55-43a1-8e9d-0135e976a924,7f63076c-8f55-43a1-8e9d-0135e976a924,ee3a333f-539e-4916-b4ec-ce162c697376,ee3a333f-539e-4916-b4ec-ce162c697376,ee3a333f-539e-4916-b4ec-ce162c697376,...,9a4c7ac3-5a83-44e0-9392-c846ffc99412,9a4c7ac3-5a83-44e0-9392-c846ffc99412,0d8e5d95-afe8-4fd0-9edf-c782a78823c1,0d8e5d95-afe8-4fd0-9edf-c782a78823c1,0d8e5d95-afe8-4fd0-9edf-c782a78823c1,0d8e5d95-afe8-4fd0-9edf-c782a78823c1,0d8e5d95-afe8-4fd0-9edf-c782a78823c1,0d8e5d95-afe8-4fd0-9edf-c782a78823c1,0d8e5d95-afe8-4fd0-9edf-c782a78823c1,bcb6eaac-42ee-4678-a4bf-f239e8d66e23
mapName,Baltic_Main,Baltic_Main,Baltic_Main,Baltic_Main,Baltic_Main,Baltic_Main,Baltic_Main,Savage_Main,Savage_Main,Savage_Main,...,Desert_Main,Desert_Main,Chimera_Main,Chimera_Main,Chimera_Main,Chimera_Main,Chimera_Main,Chimera_Main,Chimera_Main,Tutorial_Main
gameMode,solo,solo,solo,solo,solo,solo,solo,duo,duo,duo,...,duo,duo,squad,squad,squad,squad,squad,squad,squad,solo
createdAt,2026-01-26T23:41:48Z,2026-01-26T23:41:48Z,2026-01-26T23:41:48Z,2026-01-26T23:41:48Z,2026-01-26T23:45:48Z,2026-01-26T23:45:48Z,2026-01-26T23:45:48Z,2026-01-26T23:45:23Z,2026-01-26T23:45:23Z,2026-01-26T23:45:23Z,...,2026-01-27T07:30:10Z,2026-01-27T07:30:10Z,2026-01-27T07:37:44Z,2026-01-27T07:37:44Z,2026-01-27T07:37:44Z,2026-01-27T07:37:44Z,2026-01-27T07:37:44Z,2026-01-27T07:37:44Z,2026-01-27T07:37:44Z,2026-01-27T07:57:40Z
DBNOs,0,0,0,0,0,0,0,0,1,0,...,1,3,4,1,0,1,1,5,1,0
assists,0,0,0,0,0,0,0,0,1,0,...,0,2,0,1,0,0,0,1,0,0
boosts,7,0,5,4,5,9,5,4,5,0,...,1,6,4,3,0,0,7,8,0,0
damageDealt,170.85225,397.84018,1871.5366,1217.2446,322.613,680.7937,202.92502,194.375,650.48486,0.0,...,228.43372,217.74243,540.7289,99.57571,0.0,179.93295,267.32376,934.6811,146.2,0.0
deathType,byzone,byplayer,alive,byplayer,byplayer,alive,byplayer,byplayer,alive,byplayer,...,byplayer,byzone,byplayer,alive,byplayer,byplayer,byplayer,alive,byplayer,logout
headshotKills,1,0,5,2,1,2,1,0,3,0,...,0,0,4,1,0,0,1,3,1,0
heals,1,0,4,0,0,0,0,3,2,0,...,0,7,1,1,0,0,8,6,0,0
killPlace,6,3,1,2,8,1,3,9,2,99,...,6,24,2,15,57,22,3,1,24,1
killStreaks,1,1,2,1,1,1,2,1,2,0,...,2,1,3,1,0,1,1,2,1,0
kills,2,4,21,12,2,7,4,2,5,0,...,3,1,7,1,0,1,3,9,1,0
longestKill,43.184418,74.53809,308.65994,286.69388,261.7395,221.495,122.774666,26.28303,139.5951,0.0,...,128.88194,132.209,145.31337,94.25189,0.0,2.123384,15.190188,141.5362,34.25638,0.0
name,Verry94,wiuu55_ff,x3xnabi,suk0114,HK__lee,e_hansol,GMP_anuglyPotato,54237957,chs_louis_,rapstudent20,...,burgundy_buldak,ayomiya_98,sinjukuking,v030b,qmffnqkefqlc,MINJI_106,phoenix-pjh,cocaine_lover123,dlstjdqhth,Logan_0927
playerId,account.39008c8ee79642f6b422e350d56230bf,account.6221f63a6ad747b497e731627b15ec02,account.f17258bb29f348fc9152fb694b5c8285,account.50f67a6b5d33425e9bd3cee8e6b7ec75,account.dea35f68864647dc8c059d73d2a16c74,account.637b6b3ce24e4cb1ba52eba1a647f868,account.771a33bf9fe541bdac70d3b521ed7456,account.e2d5df72ee614d9b81ed932d907e592f,account.9a3a39626ec44213812e709e9d875c58,account.3047f65d7bef4d53b298a71f68eaa69b,...,account.1374eec9496d47f3b2fdd398f1637e07,account.6c8f55088d6a4e0db0777b9080ea3606,account.1cd42e290dcd47c489192732c9cc6979,account.09c2f9adc1454ecc8a95d98d8be2b367,account.97ff609ddefc403c998c3d1c29400787,account.2402eaa8567c45ea907f82f7ebeb35f0,account.7c2f40e8f2f941288d580fc2173c95e9,account.9060406ce27e46dcb61eda38f2b53142,account.321f40d09c164b1499ca1167d35e8c00,account.18a92cb1dbae490a8f9871b987043381
revives,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
rideDistance,2256.599,2750.8596,5775.3306,79.235176,3854.556,3883.1519,4633.842,3443.7183,0.0,0.0,...,2720.7039,6701.952,0.0,0.0,0.0,0.0,0.0,2.365976,0.0,0.0
roadKills,0,0,4,0,0,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,0
swimDistance,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
teamKills,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
timeSurvived,1184,1067,1511,1480,1310,1351,793,1430,1433,154,...,1240,1336,1250,1253,483,647,1167,1253,492,161
vehicleDestroys,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
walkDistance,4067.791,1568.3281,2363.5908,4400.385,1745.0322,2451.645,1280.8557,2892.0376,3796.8245,193.12973,...,2599.787,3098.4004,3823.2517,3476.025,2317.2327,1968.7289,3187.4062,2858.578,2018.4186,10.306934
weaponsAcquired,11,13,13,8,8,15,9,9,13,2,...,7,11,6,11,4,5,11,8,4,0
winPlace,20,31,1,4,3,1,41,2,1,50,...,7,4,2,1,14,13,3,1,14,1

In [11]:
df_tele.T

,0,1,2,3,4,5,6,7,8,9,...,36162,36163,36164,36165,36166,36167,36168,36169,36170,36171
MatchId,match.bro.competitive.pc-2018-39.kakao.squad.k...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PingQuality,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
_D,2026-01-27T01:39:18.8256559Z,2026-01-27T01:38:09.968Z,2026-01-27T01:38:09.994Z,2026-01-27T01:38:09.994Z,2026-01-27T01:38:10.007Z,2026-01-27T01:38:10.053Z,2026-01-27T01:38:10.068Z,2026-01-27T01:38:10.069Z,2026-01-27T01:38:10.186Z,2026-01-27T01:38:10.190Z,...,2026-01-27T02:04:39.264Z,2026-01-27T02:04:43.711Z,2026-01-27T02:04:43.811Z,2026-01-27T02:04:47.253Z,2026-01-27T02:04:51.695Z,2026-01-27T02:04:51.828Z,2026-01-27T02:04:55.269Z,2026-01-27T02:04:59.711Z,2026-01-27T02:04:59.811Z,2026-01-27T02:05:03.251Z
_T,LogMatchDefinition,LogPlayerLogin,LogPlayerCreate,LogPlayerLogin,LogPlayerCreate,LogPlayerLogin,LogPlayerCreate,LogPlayerLogin,LogPlayerCreate,LogPlayerLogin,...,LogHeal,LogHeal,LogHeal,LogHeal,LogHeal,LogHeal,LogHeal,LogHeal,LogHeal,LogHeal
accountId,NaN,account.98475b7e0b6e42a091a8174fee812abb,NaN,account.74ba67fc414742c896450c6d302b4208,NaN,account.47a94b48a3a34deda7072b067996f6a6,NaN,account.94d64e73ebee42aa8fecbbc10c3aae44,NaN,account.6d43057fd515460192222cf93b9ee846,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
wheelIndex,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
carePackageUniqueId,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
carePackageName,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
allWeaponStats,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gameResultOnFinished.results,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
index = np.where(df_tele.isnull().sum() == 36172) #(array([  1,  22, 157, 273, 300, 319, 324], dtype=int64),)
df_tele.columns[index]

Index(['PingQuality', 'vehicle', 'victimGameResult.gameResult', 'dBNOMaker',
       'reviver.inSpecialZone', 'instigator.inSpecialZone', 'attacker'],
      dtype='object')

In [33]:
df_tele['_T'].unique()

array(['LogMatchDefinition', 'LogPlayerLogin', 'LogPlayerCreate',
       'LogPlayerPosition', 'LogObjectInteraction', 'LogPlayerAttack',
       'LogVaultStart', 'LogMatchStart', 'LogVehicleRide', 'LogItemEquip',
       'LogItemPickup', 'LogPlayerLogout', 'LogGameStatePeriodic',
       'LogVehicleLeave', 'LogItemUnequip', 'LogParachuteLanding',
       'LogObjectDestroy', 'LogItemAttach', 'LogItemDrop', 'LogItemUse',
       'LogItemDetach', 'LogPlayerTakeDamage', 'LogPlayerMakeGroggy',
       'LogWeaponFireCount', 'LogPhaseChange', 'LogPlayerKillV2',
       'LogVehicleDamage', 'LogArmorDestroy', 'LogItemPickupFromLootBox',
       'LogHeal', 'LogPlayerUseThrowable', 'LogItemPutToVehicleTrunk',
       'LogSpecialZoneInCharacters', 'LogItemPickupFromVehicleTrunk',
       'LogCarePackageSpawn', 'LogPlayerRevive', 'LogCarePackageLand',
       'LogSwimStart', 'LogSwimEnd', 'LogEmPickupLiftOff',
       'LogWheelDestroy', 'LogItemPickupFromCarepackage',
       'LogVehicleDestroy', 'LogMatchEnd'], dtype=object)